version: '3.7'
services:
    nginx:
        container_name: nginx-server-dev
        ports:
            - "8080:8080"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./nuxt-client/dist:/usr/share/nginx/html
        networks:
            - backend

    postgres:
        container_name: postgres-dev
        volumes:
            - ./postgres/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
            - db-data:/var/lib/postgresql/data
        env_file:
          - ./env_files/postgres.env
        ports:
            - "5432:5432"
        networks:
            - backend

    authorization:
        container_name: authorization-server-dev
        volumes:
            - ./authorization-server/users/migrations:/authorization-server/users/migrations
        environment:
            EXPOSED_PORT: 8086
        env_file:
            - ./env_files/postgres.env
            - ./env_files/common-django.env
        build:
            context: ./authorization-server
            dockerfile: Dockerfile
        ports:
            - "8086:8086"
        networks:
            - backend

    application:
        container_name: application-server-dev
        volumes:
            - ./application-server/users/migrations:/application-server/users/migrations
        environment:
            EXPOSED_PORT: 8087
        env_file:
            - ./env_files/postgres.env
            - ./env_files/common-django.env
        build:
            context: ./application-server
            args:
                port: 8087
            dockerfile: Dockerfile
        ports:
            - "8087:8087"
        networks:
            - backend

    resource:
        container_name: resource-server-dev
        volumes:
            - ./resource-server/recipes/migrations:/resource-server/recipes/migrations
            - ./resource-server/unicorns/migrations:/resource-server/unicorns/migrations
        environment:
            EXPOSED_PORT: 8088
        env_file:
            - ./env_files/postgres.env
            - ./env_files/common-django.env
        build:
            context: ./resource-server
            args:
                port: 8088
            dockerfile: Dockerfile
        ports:
            - "8088:8088"
        networks:
            - backend

networks:
    backend:
        name: backend_network
        driver: bridge

volumes:
    db-data:
        name: data_volume
