version: '3.7'
services:
    nginx:
        image: nginx:1.17
        depends_on:
            - authorization
            - application
            - resource

    postgres:
        image: postgres:12.2

    authorization:
        image: authorization_server
        depends_on:
            - postgres

    application:
        image: application_server
        depends_on:
            - postgres

    resource:
        image: resource_server
        depends_on:
            - postgres
